name: VSCODE Hasicorp x InvisiRisk

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@v1.0.29
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_STAGE }}

      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@v1.0.29
        with:
          cleanup: "true"
          
      - name: Gather Job status
        if: always()
        uses: invisirisk/pse-action@v1.0.29
        with:
          get_jobs: "true"
