name: VSCODE Hasicorp x InvisiRisk

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_PROD_CHART }}

      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
          cleanup_step_name: "Cleanup PSE"
          debug: "true"
          # send_job_status: "true" # enables github workflow jobs information

  gather_analytics:
     runs-on: ubuntu-latest
     name: Gather Analytics
     needs: test
     if: always()
     steps:
      - name: Gather Status
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_PROD_CHART }}
          send_job_status: "true"
